version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # persist data even if container shuts down
    ports:
      - "5432:5432"
      -
volumes:
  database-data-vava:
